#include "languagehelper.h"

#include <QCoreApplication>
#include <QQmlApplicationEngine>
#include <QDebug>

LanguageHelper::LanguageHelper(QQmlApplicationEngine *engine, QObject *parent)
    : QObject(parent)
    , m_engine(engine)
{
}

void LanguageHelper::setLanguage(const QString &lang)
{
    // Remove the old translator to restore English (English is the source language).
    QCoreApplication::removeTranslator(&m_translator);
    m_current = (lang == QLatin1String("zh_CN")) ? QStringLiteral("zh_CN") : QStringLiteral("en");

    if (m_current == QLatin1String("zh_CN")) {
        // The .qm is generated by CMake qt_add_lrelease and embedded at /i18n/.
        if (!m_translator.load(QStringLiteral(":/i18n/sy1000_zh_CN.qm"))) {
            qWarning() << "Failed to load zh_CN translation: :/i18n/sy1000_zh_CN.qm";
            m_current = QStringLiteral("en");
        } else {
            QCoreApplication::installTranslator(&m_translator);
        }
    }

    // Re-evaluate qsTr() in already-loaded QML.
    m_engine->retranslate();
    emit currentChanged();
}

QString LanguageHelper::current() const
{
    return m_current;
}
